spring.application.name=JobAgentBackend

app.frontend.url=${FRONTEND_URL:http://localhost:5173}

#--- database connections
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


#--hibernate and jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

gmail.redirect.uri=${GMAIL_REDIRECT_URI:http://localhost:5173/gmail/callback}
gmail.encryption.key=${GMAIL_ENCRYPTION_KEY}
google.client.id=${GOOGLE_CLIENT_ID}
google.client.secret=${GOOGLE_CLIENT_SECRET}
github.client.id=${GITHUB_CLIENT_ID}
github.client.secret=${GITHUB_CLIENT_SECRET}
adzuna.app.id=${ADZUNA_APP_ID}
adzuna.app.key=${ADZUNA_APP_KEY}
jooble.api.key=${JOOBLE_API_KEY}
gemini.api.key=${GEMINI_API_KEY}
groq.api.key=${GROQ_API_KEY}
groq.fallback.api.key=${GROQ_FALLBACK_API_KEY}
openrouter.api.key=${OPEN_ROUTER_API_KEY}
jwt.secret.key=${SECRET_KEY}
cookie.secure=${COOKIE_SECURE:false}
